version: '3.8'

services:
  videocraft:
    image: videocraft:241030
    container_name: videocraft
    volumes:
      - /exports:/exports
    tty: true
    command: bash
    ports:
        - "8822:22"
